server:
  port: 8800

spring:
  application:
    name: spotify-service


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG