apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzcw==
  POSTGRES_DB: bXVzaWNfcmVjb21tZW5kZXI=
  JWT_SECRET: d05def16a48626476c83ff9033197adf05b0b43fb25acc8ad6b1f53d6ecfb7b7