server:
  port: 8761

eureka:
  instance:
    hostname: discovery-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    server:
      enable-self-preservation: false
      wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: discovery-server
  cloud:
    config:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.netflix.eureka: debug
    com.netflix.discovery: debug