apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: music-recommender/discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "discovery-server"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"